server:
  port: 8081

spring:
  application:
    name: microservice-document

  data:
    mongodb:
      uri: mongodb://mongo:mongo@localhost:10002/local?authSource=admin

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
